version: '3.1'

services:
  ledgero-api-db:
    image: docker.io/postgres
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - "5462:5432"

  ledgero-api-memcached:
    image: docker.io/memcached
    restart: always
    ports:
      - "11211:11211"
