[package]
name = "ledgero-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ledgero-server = { path = "../server" }
tokio = { version = "1.27.0", features = ["rt"] }
