[package]
name = "entity-macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dev-dependencies]
trybuild = { version = "1.0.75", features = ["diff"] }

[dependencies]
convert_case = "0.6.0"
quote = "1.0.23"
syn = { version = "1.0.107", features = ["extra-traits"] }
